---

- name: UFW | Notify if no rules are defined
  ansible.builtin.pause:
    prompt: 'You have not defined any ufw-rules! Only the generic ssh-rule will be processed. Do you want to continue?'
  when: >
    ufw_rules is undefined or
    ufw_rules is none or
    ufw_rules|length == 0
  tags: [ufw, firewall]

- name: UFW | Install package
  ansible.builtin.apt:
    name: ['ufw']
    state: present
  tags: [ufw, firewall]

- name: UFW | Set defaults
  ansible.builtin.template:
    src: 'templates/etc/default/ufw.j2'
    dest: '/etc/default/ufw'
    owner: 'root'
    group: 'root'
    mode: 0644
  when: configure_ufw_basics
  notify: reload_ufw
  tags: [ufw, firewall]

- name: UFW | Stateless rules
  ansible.builtin.import_tasks: stateless.yml
  when: >
    ((ufw_reset_rules is defined and ufw_reset_rules) or
    (ufw_stateful is defined and not ufw_stateful)) and
    ufw_rules is defined and
    ufw_rules | length > 0
  tags: [ufw, firewall]

- name: UFW | Checking ssh rule
  ansible.builtin.import_tasks: rule/ssh.yml
  when: configure_ufw_ssh_rule
  tags: [ufw, firewall]

- name: UFW | Stateful rules
  ansible.builtin.import_tasks: stateful.yml
  when: >
    ((ufw_reset_rules is defined and not ufw_reset_rules) or
    (ufw_stateful is defined and ufw_stateful)) and
    ufw_rules is defined and
    ufw_rules | length > 0
  tags: [ufw, firewall]

- name: UFW | Set logging
  community.general.ufw:
    logging: "{{ ufw_config.logging | default(defaults_ufw.logging) }}"
  when: configure_ufw_basics
  notify: reload_ufw
  tags: [ufw, firewall]

- name: UFW | Enable ufw
  community.general.ufw:
    state: enabled
  tags: [ufw, firewall]
